activite:
    resource: "@ActiviteBundle/Resources/config/routing.yml"
    prefix:   /

activite_categorie:
    resource: "@ActiviteBundle/Controller/CategorieController.php"
    type:     annotation

activite_animateur:
    resource: "@ActiviteBundle/Controller/AnimateurController.php"
    type:     annotation

activite_activite:
    resource: "@ActiviteBundle/Controller/ActiviteController.php"
    type:     annotation


gestion:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /Gestion

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

enfants:
    resource: "@EnfantsBundle/Resources/config/routing.yml"
    prefix:   /enfants

classe:
    resource: "@classeBundle/Resources/config/routing.yml"
    prefix:   /classe

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


